spring:
 application:
  name: authorization-server
<<<<<<< HEAD
 
=======

>>>>>>> a5eb3bd24e51b60c2c7df64867a05eb33751399b
 jpa:
  hibernate:
   ddl-auto: validate

 datasource:
  url: ${DB_URL}
  username: ${DB_USER}
  password: ${DB_PASS}
  driver-class-name: oracle.jdbc.OracleDriver

server:
 port: 9000